### PR TITLE
Fixed the Onboarding Page Setup

### LINKED ISSUE #473: New Onboarding page for PictoPy
https://pictopy-new-frontend.vercel.app/

Get the image icons from here: https://github.com/rahulharpal1603/pictopy_frontend_prototype/tree/main/public

**Visit the above site in incognito mode** and see the onboarding page. We have to implement this type of page for PictoPy. There are theme changes, though, in dark mode, the UI should look like the image below(use standard ShadCN components like used in UpdateDialog.tsx), not like the dark blue theme of the above site: 

Image

Before all these steps are done, we are checking for updates, and we should not touch that. Try to understand how onboarding is working, then explain your approach before starting to code.

### PR DESCRIPTION
**Pull request by ssz2605**
# Implemented Complete Onboarding Flow: Avatar, Name, Folder, and Theme Steps

This PR implements the full onboarding flow for PictoPy, including AvatarandNameSelection, FolderSetupStep, and ThemeSelection, fully aligned with Redux state management.

## Key Changes

1. **Avatar & Name Selection**
   - Combined AvatarSelection and NameSelection into a single component for simplicity.
   - Managed state using **Redux**, removing reliance on local state.

2. **Theme Selection**
   - Implemented theme selection logic.
   - State is managed via Redux and synced with local storage for persistence.

3. **Folder Setup Step**
   - Updated `SetUpScreen` inside FolderSetupStep to use Redux for state management, keeping consistency across onboarding steps.

4. **Onboarding Steps Integration**
   - Imported and rendered the new steps (`AvatarSelection` and `ThemeSelection`) alongside existing steps like `FolderSetupStep`.
   - Updated the `STEPS` array in `Steps.tsx` to include the new steps, maintaining correct flow order.

5. **Onboarding Slice Updates**
   - Extended `OnboardingState` and reducers in `onboardingSlice` to handle `avatar` and `name`.

closes #473 

## Summary by CodeRabbit

- New Features
  - Added Avatar Selection and Theme Selection onboarding steps with progress indicators, Back/Next navigation, name input, and avatar picker with validation.
  - Theme options: Light, Dark, and System; preference is persisted and applied app-wide.
  - Folder selection step updated with clearer controls and two-panel layout.
  - Introduced rotating feature preview showcasing app highlights.
- Refactor
  - Unified onboarding flow into a consistent two-card layout.
- Chores
  - Added UI dependencies for label and radio controls.

### CODE REVIEW

**Comment by ssz2605** [comment]
@rahulharpal1603 I will make the required changes.

**Comment by rahulharpal1603** [comment]
> @rahulharpal1603 I will make the required changes.

Hi,
what is the status?

**Comment by ssz2605** [comment]
@rahulharpal1603 Sorry for the delay , will be completing it in the next 2-3 days  at max  .

**Comment by ssz2605** [comment]
@rahulharpal1603 Now can you please review the changes.

File: frontend/src/constants/steps.ts [hunk 1]
```diff
@@ -1,4 +1,5 @@
 export const STEPS = {
-  UPDATE_STEP: 'updates',
+  AVATAR_SELECTION_STEP: 'avatarSelection',
   FOLDER_SETUP_STEP: 'folderSetup',
+  THEME_SELECTION_STEP: 'themeSelection',
 };
```
Comment (rahulharpal1603) [inline frontend/src/constants/steps.ts]: The Update step is missing here, it should be after theme selection

File: frontend/src/components/OnboardingSteps/OnboardingStep.tsx [hunk 2]
```diff
@@ -1,25 +1,55 @@
...
+        return <ThemeSelectionStep {...sharedProps} />;
+      default:
+        return <div></div>;
+    }
+  };
+
+  return (
+    <div className="bg-background text-foreground flex min-h-screen w-full items-center justify-center p-10">
+      <div className="w-full max-w-4xl">{renderStepComponent()}</div>
+    </div>
```
Comment (rahulharpal1603) [inline frontend/src/components/OnboardingSteps/OnboardingStep.tsx]: Add the case for update step also.

File: frontend/src/components/OnboardingSteps/ThemeSelectionStep.tsx [hunk 3]
```diff
@@ -0,0 +1,204 @@
...
+                  className={`h-2 w-2 rounded-full ${
+                    index === featureIndex
+                      ? 'bg-foreground'
+                      : 'bg-muted-foreground/40'
+                  }`}
+                />
+              ))}
+            </div>
+          </div>
+        </Card>
```
Comment (rahulharpal1603) [inline frontend/src/components/OnboardingSteps/ThemeSelectionStep.tsx]: This Right Card is common for all the three onboarding pages, therefore extract the logic to a separate component to encourage reuse.

File: frontend/src/components/OnboardingSteps/AvatarSelectionStep.tsx [hunk 4]
```diff
@@ -0,0 +1,202 @@
...
+                  className={`h-2 w-2 rounded-full ${
+                    index === featureIndex
+                      ? 'bg-foreground'
+                      : 'bg-muted-foreground/40'
+                  }`}
+                />
+              ))}
+            </div>
+          </CardContent>
+        </Card>
```
Comment (rahulharpal1603) [inline frontend/src/components/OnboardingSteps/AvatarSelectionStep.tsx]: Move it to a separate component and reuse it for other onboarding steps.

File: frontend/src/components/OnboardingSteps/FolderSetupStep.tsx [hunk 5]
```diff
@@ -1,35 +1,196 @@
...
+                      ? 'bg-foreground'
+                      : 'bg-muted-foreground/40'
+                  }`}
+                />
+              ))}
+            </div>
+          </CardContent>
+
+          <CardFooter className="p-0" />
+        </Card>
```
Comment (rahulharpal1603) [inline frontend/src/components/OnboardingSteps/FolderSetupStep.tsx]: Same as the other two, move it to a separate component.

**Comment by rahulharpal1603** [comment]
> @rahulharpal1603 Now can you please review the changes.

I have requested some small changes; please apply those changes.

**Comment by rahulharpal1603** [comment]
@ssz2605 any updates? This was the final review, after the changes are made I will be merging the PR.

**Comment by ssz2605** [comment]
@rahulharpal1603 I'm currently working on the changes and will update the PR soon. Apologies for the delay, I’ve been tied up with a hectic schedule.

**Comment by rahulharpal1603** [comment]
@ssz2605 Thanks for the contribution!

**Comment by ssz2605** [comment]
Thanks for your guidance in resolving this issue, @rahulharpal1603.
